[package]
name = "ipc_subtitles_example"
version = "0.1.0"
edition = "2021"

[dependencies]
single_instance_app = { path = ".." }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
